<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.0.4 (Python 3.6.3 on win32)" generated="20180517 12:54:01.244">
<suite id="s1" name="runECCautomation" source="C:\Users\madduv\TAecc\src\runECCautomation.robot">
<test id="s1-t1" name="Test provisionVM">
<kw name="provision vm with iso">
<msg timestamp="20180517 12:54:01.588" level="FAIL">No keyword with name 'provision vm with iso' found.</msg>
<status status="FAIL" starttime="20180517 12:54:01.588" endtime="20180517 12:54:01.588"></status>
</kw>
<status status="FAIL" starttime="20180517 12:54:01.588" endtime="20180517 12:54:01.588" critical="yes">No keyword with name 'provision vm with iso' found.</status>
</test>
<test id="s1-t2" name="Test addDiskToVM">
<kw name="action add disk">
<msg timestamp="20180517 12:54:01.603" level="FAIL">No keyword with name 'action add disk' found.</msg>
<status status="FAIL" starttime="20180517 12:54:01.603" endtime="20180517 12:54:01.603"></status>
</kw>
<status status="FAIL" starttime="20180517 12:54:01.588" endtime="20180517 12:54:01.603" critical="yes">No keyword with name 'action add disk' found.</status>
</test>
<test id="s1-t3" name="Test addDNICToVM">
<kw name="action add nic">
<msg timestamp="20180517 12:54:01.603" level="FAIL">No keyword with name 'action add nic' found.</msg>
<status status="FAIL" starttime="20180517 12:54:01.603" endtime="20180517 12:54:01.603"></status>
</kw>
<status status="FAIL" starttime="20180517 12:54:01.603" endtime="20180517 12:54:01.603" critical="yes">No keyword with name 'action add nic' found.</status>
</test>
<test id="s1-t4" name="Test removeDiskfromVM">
<kw name="action remove disk">
<msg timestamp="20180517 12:54:01.619" level="FAIL">No keyword with name 'action remove disk' found.</msg>
<status status="FAIL" starttime="20180517 12:54:01.619" endtime="20180517 12:54:01.619"></status>
</kw>
<status status="FAIL" starttime="20180517 12:54:01.603" endtime="20180517 12:54:01.619" critical="yes">No keyword with name 'action remove disk' found.</status>
</test>
<test id="s1-t5" name="Test powerOffVM">
<kw name="action power off vm">
<msg timestamp="20180517 12:54:01.619" level="FAIL">No keyword with name 'action power off vm' found.</msg>
<status status="FAIL" starttime="20180517 12:54:01.619" endtime="20180517 12:54:01.619"></status>
</kw>
<status status="FAIL" starttime="20180517 12:54:01.619" endtime="20180517 12:54:01.619" critical="yes">No keyword with name 'action power off vm' found.</status>
</test>
<test id="s1-t6" name="Test removeNICfromVM">
<kw name="action remove nic">
<msg timestamp="20180517 12:54:01.635" level="FAIL">No keyword with name 'action remove nic' found.</msg>
<status status="FAIL" starttime="20180517 12:54:01.635" endtime="20180517 12:54:01.635"></status>
</kw>
<status status="FAIL" starttime="20180517 12:54:01.619" endtime="20180517 12:54:01.635" critical="yes">No keyword with name 'action remove nic' found.</status>
</test>
<test id="s1-t7" name="Test reconfigureHwTemplate">
<kw name="action reconfigure hw template">
<msg timestamp="20180517 12:54:01.635" level="FAIL">No keyword with name 'action reconfigure hw template' found.</msg>
<status status="FAIL" starttime="20180517 12:54:01.635" endtime="20180517 12:54:01.635"></status>
</kw>
<status status="FAIL" starttime="20180517 12:54:01.635" endtime="20180517 12:54:01.635" critical="yes">No keyword with name 'action reconfigure hw template' found.</status>
</test>
<test id="s1-t8" name="Test powerOnVM">
<kw name="action power on vm">
<msg timestamp="20180517 12:54:01.650" level="FAIL">No keyword with name 'action power on vm' found.</msg>
<status status="FAIL" starttime="20180517 12:54:01.650" endtime="20180517 12:54:01.650"></status>
</kw>
<status status="FAIL" starttime="20180517 12:54:01.635" endtime="20180517 12:54:01.650" critical="yes">No keyword with name 'action power on vm' found.</status>
</test>
<status status="FAIL" starttime="20180517 12:54:01.244" endtime="20180517 12:54:01.650"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="8">Critical Tests</stat>
<stat pass="0" fail="8">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="8" id="s1" name="runECCautomation">runECCautomation</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20180517 12:54:01.400" level="ERROR">Error in file 'C:\Users\madduv\TAecc\src\runECCautomation.robot': Importing test library 'provision_vm_with_iso' failed: ModuleNotFoundError: No module named 'exceptions'
Traceback (most recent call last):
  File "C:\Users\madduv\TAecc\src\provision_vm_with_iso.py", line 3, in &lt;module&gt;
    import library.helpers as help
  File "C:\Users\madduv\TAecc\src\library\helpers.py", line 2, in &lt;module&gt;
    import exceptions
PYTHONPATH:
  C:\Python
  C:\Python\Lib\site-packages
  C:\Python27
  C:\Python27\Lib\site-packages
  C:\Users\madduv\PycharmProjects\veche-ta
  C:\Users\madduv\PycharmProjects\webdemo
  c:\python\python36.zip
  c:\python\DLLs
  c:\python\lib</msg>
<msg timestamp="20180517 12:54:01.424" level="ERROR">Error in file 'C:\Users\madduv\TAecc\src\runECCautomation.robot': Importing test library 'add_disk' failed: ModuleNotFoundError: No module named 'exceptions'
Traceback (most recent call last):
  File "C:\Users\madduv\TAecc\src\add_disk.py", line 3, in &lt;module&gt;
    import library.helpers as help
  File "C:\Users\madduv\TAecc\src\library\helpers.py", line 2, in &lt;module&gt;
    import exceptions
PYTHONPATH:
  C:\Python
  C:\Python\Lib\site-packages
  C:\Python27
  C:\Python27\Lib\site-packages
  C:\Users\madduv\PycharmProjects\veche-ta
  C:\Users\madduv\PycharmProjects\webdemo
  c:\python\python36.zip
  c:\python\DLLs
  c:\python\lib</msg>
<msg timestamp="20180517 12:54:01.448" level="ERROR">Error in file 'C:\Users\madduv\TAecc\src\runECCautomation.robot': Importing test library 'add_nic' failed: ModuleNotFoundError: No module named 'exceptions'
Traceback (most recent call last):
  File "C:\Users\madduv\TAecc\src\add_nic.py", line 3, in &lt;module&gt;
    import library.helpers as help
  File "C:\Users\madduv\TAecc\src\library\helpers.py", line 2, in &lt;module&gt;
    import exceptions
PYTHONPATH:
  C:\Python
  C:\Python\Lib\site-packages
  C:\Python27
  C:\Python27\Lib\site-packages
  C:\Users\madduv\PycharmProjects\veche-ta
  C:\Users\madduv\PycharmProjects\webdemo
  c:\python\python36.zip
  c:\python\DLLs
  c:\python\lib</msg>
<msg timestamp="20180517 12:54:01.480" level="ERROR">Error in file 'C:\Users\madduv\TAecc\src\runECCautomation.robot': Importing test library 'power_off_vm' failed: ModuleNotFoundError: No module named 'exceptions'
Traceback (most recent call last):
  File "C:\Users\madduv\TAecc\src\power_off_vm.py", line 2, in &lt;module&gt;
    import library.helpers as help
  File "C:\Users\madduv\TAecc\src\library\helpers.py", line 2, in &lt;module&gt;
    import exceptions
PYTHONPATH:
  C:\Python
  C:\Python\Lib\site-packages
  C:\Python27
  C:\Python27\Lib\site-packages
  C:\Users\madduv\PycharmProjects\veche-ta
  C:\Users\madduv\PycharmProjects\webdemo
  c:\python\python36.zip
  c:\python\DLLs
  c:\python\lib</msg>
<msg timestamp="20180517 12:54:01.494" level="ERROR">Error in file 'C:\Users\madduv\TAecc\src\runECCautomation.robot': Importing test library 'power_on_vm' failed: ModuleNotFoundError: No module named 'exceptions'
Traceback (most recent call last):
  File "C:\Users\madduv\TAecc\src\power_on_vm.py", line 2, in &lt;module&gt;
    import library.helpers as help
  File "C:\Users\madduv\TAecc\src\library\helpers.py", line 2, in &lt;module&gt;
    import exceptions
PYTHONPATH:
  C:\Python
  C:\Python\Lib\site-packages
  C:\Python27
  C:\Python27\Lib\site-packages
  C:\Users\madduv\PycharmProjects\veche-ta
  C:\Users\madduv\PycharmProjects\webdemo
  c:\python\python36.zip
  c:\python\DLLs
  c:\python\lib</msg>
<msg timestamp="20180517 12:54:01.525" level="ERROR">Error in file 'C:\Users\madduv\TAecc\src\runECCautomation.robot': Importing test library 'remove_disk' failed: ModuleNotFoundError: No module named 'exceptions'
Traceback (most recent call last):
  File "C:\Users\madduv\TAecc\src\remove_disk.py", line 3, in &lt;module&gt;
    import library.helpers as help
  File "C:\Users\madduv\TAecc\src\library\helpers.py", line 2, in &lt;module&gt;
    import exceptions
PYTHONPATH:
  C:\Python
  C:\Python\Lib\site-packages
  C:\Python27
  C:\Python27\Lib\site-packages
  C:\Users\madduv\PycharmProjects\veche-ta
  C:\Users\madduv\PycharmProjects\webdemo
  c:\python\python36.zip
  c:\python\DLLs
  c:\python\lib</msg>
<msg timestamp="20180517 12:54:01.556" level="ERROR">Error in file 'C:\Users\madduv\TAecc\src\runECCautomation.robot': Importing test library 'remove_nic' failed: ModuleNotFoundError: No module named 'exceptions'
Traceback (most recent call last):
  File "C:\Users\madduv\TAecc\src\remove_nic.py", line 3, in &lt;module&gt;
    import library.helpers as help
  File "C:\Users\madduv\TAecc\src\library\helpers.py", line 2, in &lt;module&gt;
    import exceptions
PYTHONPATH:
  C:\Python
  C:\Python\Lib\site-packages
  C:\Python27
  C:\Python27\Lib\site-packages
  C:\Users\madduv\PycharmProjects\veche-ta
  C:\Users\madduv\PycharmProjects\webdemo
  c:\python\python36.zip
  c:\python\DLLs
  c:\python\lib</msg>
<msg timestamp="20180517 12:54:01.572" level="ERROR">Error in file 'C:\Users\madduv\TAecc\src\runECCautomation.robot': Importing test library 'reconfigure_hw_template' failed: ModuleNotFoundError: No module named 'exceptions'
Traceback (most recent call last):
  File "C:\Users\madduv\TAecc\src\reconfigure_hw_template.py", line 3, in &lt;module&gt;
    import library.helpers as help
  File "C:\Users\madduv\TAecc\src\library\helpers.py", line 2, in &lt;module&gt;
    import exceptions
PYTHONPATH:
  C:\Python
  C:\Python\Lib\site-packages
  C:\Python27
  C:\Python27\Lib\site-packages
  C:\Users\madduv\PycharmProjects\veche-ta
  C:\Users\madduv\PycharmProjects\webdemo
  c:\python\python36.zip
  c:\python\DLLs
  c:\python\lib</msg>
</errors>
</robot>
